/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imat.panels.contentPanels;

import imat.models.CustomerModel;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Viktor
 */
public class PanelDeliveryInfo extends javax.swing.JPanel {

    /**
     * Creates new form PanelDeliveryInfo
     */
    public PanelDeliveryInfo() {
        initComponents();
        firstNameTextField.setText(CustomerModel.getFirstName());
        lastNameTextField.setText(CustomerModel.getLastName());
        addressTextField.setText(CustomerModel.getAddress());
        postCodeTextField.setText(CustomerModel.getPostCode());
        postAddressTextField.setText(CustomerModel.getPostAddress());
        phoneNumberTextField.setText(CustomerModel.getPhoneNumber());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        careOfLabel = new javax.swing.JLabel();
        addressTextField = new javax.swing.JTextField();
        careOfTextField = new javax.swing.JTextField();
        postCodeLabel = new javax.swing.JLabel();
        postAddressLabel = new javax.swing.JLabel();
        postAddressTextField = new javax.swing.JTextField();
        phoneNumberLabel = new javax.swing.JLabel();
        postCodeTextField = new javax.swing.JFormattedTextField();
        phoneNumberTextField = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        informationTextArea = new javax.swing.JTextArea();
        mobileNumberTextField = new javax.swing.JFormattedTextField();
        mobileNumberLabel = new javax.swing.JLabel();
        infoTextLabel = new javax.swing.JLabel();
        cardHolderReminderLabel = new javax.swing.JLabel();
        firstNameErrorLabel = new javax.swing.JLabel();
        addressErrorLabel = new javax.swing.JLabel();
        postCodeErrorLabel = new javax.swing.JLabel();
        phoneErrorLabel = new javax.swing.JLabel();
        lastNameErrorLabel = new javax.swing.JLabel();
        mobileErrorLabel = new javax.swing.JLabel();
        postAddressErrorLabel = new javax.swing.JLabel();
        careOfErrorLabel = new javax.swing.JLabel();

        setOpaque(false);

        jPanel1.setOpaque(false);

        firstNameLabel.setText("Förnamn:");

        lastNameLabel.setText("Efternamn:");

        firstNameTextField.setText("Johan");
        firstNameTextField.setAutoscrolls(false);
        firstNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstNameTextFieldFocusGained(evt);
            }
        });

        lastNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastNameTextFieldFocusGained(evt);
            }
        });

        addressLabel.setText("Gaturadress:");

        careOfLabel.setText("C/O:");

        addressTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addressTextFieldFocusGained(evt);
            }
        });

        postCodeLabel.setText("Postnummer:");

        postAddressLabel.setText("Postort:");

        postAddressTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                postAddressTextFieldFocusGained(evt);
            }
        });

        phoneNumberLabel.setText("Telefon:");

        postCodeTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        postCodeTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                postCodeTextFieldFocusGained(evt);
            }
        });

        phoneNumberTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phoneNumberTextFieldFocusGained(evt);
            }
        });

        informationTextArea.setColumns(20);
        informationTextArea.setRows(5);
        jScrollPane1.setViewportView(informationTextArea);

        mobileNumberTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mobileNumberTextFieldFocusGained(evt);
            }
        });

        mobileNumberLabel.setText("Mobil:");

        infoTextLabel.setText("Övrig information:");

        cardHolderReminderLabel.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        cardHolderReminderLabel.setText("T.ex portkod eller vånings-/lägenhetsnummer");

        firstNameErrorLabel.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        firstNameErrorLabel.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(phoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(infoTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cardHolderReminderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(firstNameLabel)
                                            .addComponent(addressLabel)
                                            .addComponent(postCodeLabel)
                                            .addComponent(phoneNumberLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(phoneErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(postCodeErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(addressErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(firstNameErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(mobileNumberTextField)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(careOfLabel)
                                            .addComponent(mobileNumberLabel)
                                            .addComponent(postAddressLabel)
                                            .addComponent(lastNameLabel))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(mobileErrorLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(postAddressErrorLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addComponent(lastNameErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(9, 9, 9))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(careOfErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(lastNameTextField)
                                    .addComponent(postAddressTextField)
                                    .addComponent(careOfTextField)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(firstNameTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(postCodeTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(164, 164, 164))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstNameLabel)
                            .addComponent(lastNameLabel)
                            .addComponent(firstNameErrorLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addressLabel)
                            .addComponent(careOfLabel)
                            .addComponent(addressErrorLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(careOfTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(postCodeLabel)
                            .addComponent(postAddressLabel)
                            .addComponent(postCodeErrorLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(postAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(postCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phoneNumberLabel)
                            .addComponent(mobileNumberLabel)
                            .addComponent(phoneErrorLabel)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lastNameErrorLabel)
                        .addGap(42, 42, 42)
                        .addComponent(careOfErrorLabel)
                        .addGap(53, 53, 53)
                        .addComponent(postAddressErrorLabel)
                        .addGap(48, 48, 48)
                        .addComponent(mobileErrorLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mobileNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(infoTextLabel)
                    .addComponent(cardHolderReminderLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstNameTextFieldFocusGained
        cancelError(firstNameTextField);
    }//GEN-LAST:event_firstNameTextFieldFocusGained

    private void lastNameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNameTextFieldFocusGained
        cancelError(lastNameTextField);
    }//GEN-LAST:event_lastNameTextFieldFocusGained

    private void postAddressTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_postAddressTextFieldFocusGained
        cancelError(postAddressTextField);
    }//GEN-LAST:event_postAddressTextFieldFocusGained

    private void postCodeTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_postCodeTextFieldFocusGained
        cancelError(postCodeTextField);
    }//GEN-LAST:event_postCodeTextFieldFocusGained

    private void phoneNumberTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneNumberTextFieldFocusGained
        cancelError(phoneNumberTextField);
    }//GEN-LAST:event_phoneNumberTextFieldFocusGained

    private void mobileNumberTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mobileNumberTextFieldFocusGained
        cancelError(mobileNumberTextField);
    }//GEN-LAST:event_mobileNumberTextFieldFocusGained

    private void addressTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressTextFieldFocusGained
        cancelError(addressTextField);
    }//GEN-LAST:event_addressTextFieldFocusGained

    public void save() {
        CustomerModel.setFirstName(firstNameTextField.getText());
        CustomerModel.setLastName(lastNameTextField.getText());
        CustomerModel.setAddress(addressTextField.getText());
        CustomerModel.setPostCode(postCodeTextField.getText());
        CustomerModel.setPostAddress(postAddressTextField.getText());
        CustomerModel.setPhoneNumber(phoneNumberTextField.getText());
    }

    public boolean isFirstNameCorrect() {
        return (CustomerModel.firstNameTest(firstNameTextField.getText()));
    }

    public boolean isLastNameCorrect() {
        return (CustomerModel.lastNameTest(lastNameTextField.getText()));
    }

    public boolean isAddressCorrect() {
        return (CustomerModel.addressTest(addressTextField.getText()));
    }

    public boolean isPostCodeCorrect() {
        return (CustomerModel.postCodeTest(postCodeTextField.getText()));
    }

    public boolean isPostAddressCorrect() {
        return (CustomerModel.postAddressTest(postAddressTextField.getText()));
    }

    public boolean isPhoneNumberCorrect() {
        return (CustomerModel.phoneNumberTest(phoneNumberTextField.getText()));
    }

    /**
     * make a textinputbox show red
     *
     * @param input what textinputbox to make red.
     */
    public void showError(JTextField input) {
        input.setBackground(new Color(240, 200, 200));
    }

    public void showLabelError(JLabel input, String str) {
        input.setText(str);
    }

    /**
     * make a textinputbox show white
     *
     * @param input what textinputbox to revert to white.
     */
    private void cancelError(JTextField input) {
        input.setBackground(Color.WHITE);
    }

    private void cancelLabelError(JLabel input) {
        input.setText("");
    }

    private void cancelAllErrors(JTextField textField, JLabel label) {
        cancelError(textField);
        cancelLabelError(label);
    }

    public void showFirstNameError() {
        showError(firstNameTextField);
        showLabelError(firstNameErrorLabel, "Namn ej korrekt ifyllt.");
    }

    public void showLastNameError() {
        showError(lastNameTextField);
        showLabelError(lastNameErrorLabel, "Namn ej korrekt ifyllt.");
    }

    public void showAddressError() {
        showError(addressTextField);
        showLabelError(addressErrorLabel, "Adress ej korrekt ifyllt.");
    }

    public void showPostCodeError() {
        showError(postCodeTextField);
        showLabelError(postCodeErrorLabel, "Postnummer ej korrekt ifyllt.");
    }

    public void showPostAddressError() {
        showError(postAddressTextField);
        showLabelError(postAddressErrorLabel, "Postadress ej korrekt ifyllt.");
    }

    public void showPhoneError() {
        showError(phoneNumberTextField);
        showLabelError(phoneErrorLabel, "Telefonnummer ej korrekt ifyllt.");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressErrorLabel;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JLabel cardHolderReminderLabel;
    private javax.swing.JLabel careOfErrorLabel;
    private javax.swing.JLabel careOfLabel;
    private javax.swing.JTextField careOfTextField;
    private javax.swing.JLabel firstNameErrorLabel;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JLabel infoTextLabel;
    private javax.swing.JTextArea informationTextArea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastNameErrorLabel;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JLabel mobileErrorLabel;
    private javax.swing.JLabel mobileNumberLabel;
    private javax.swing.JFormattedTextField mobileNumberTextField;
    private javax.swing.JLabel phoneErrorLabel;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JFormattedTextField phoneNumberTextField;
    private javax.swing.JLabel postAddressErrorLabel;
    private javax.swing.JLabel postAddressLabel;
    private javax.swing.JTextField postAddressTextField;
    private javax.swing.JLabel postCodeErrorLabel;
    private javax.swing.JLabel postCodeLabel;
    private javax.swing.JFormattedTextField postCodeTextField;
    // End of variables declaration//GEN-END:variables
}
