/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imat.panels.contentPanels.buyingPanels;

import imat.IMat;
import imat.panels.contentPanels.PanelCreditCard;
import imat.panels.contentPanels.PanelDeliveryInfo;
import javax.swing.JLabel;

/**
 *
 * @author filiplarsson
 */
public class BuyForm extends javax.swing.JPanel {
        PanelCreditCard cardPanel = new PanelCreditCard();
        PanelDeliveryInfo deliveryPanel = new PanelDeliveryInfo();
        private static boolean firstVisit = true;
    /**
     * Creates new form BuyForm
     */
    public BuyForm() {
        initComponents();
        
            System.out.println(firstVisit + " <- firstvisit");
            System.out.println(IMat.isLoggedin() + " is logged in?");
        if(firstVisit && !IMat.isLoggedin()){
            clearPanels();
            System.out.println("clearPanels");
        }else{
            System.out.println("wont clear panels");
            System.out.println(firstVisit + " <- firstvisit");
            System.out.println(IMat.isLoggedin() + " is logged in?");
        }
        
        
        jPanel1.add(cardPanel);
        jPanel1.add(new JLabel(" "));
        jPanel1.add(deliveryPanel);
      
        
            System.out.println(firstVisit + " <- firstvisit");
            System.out.println(IMat.isLoggedin() + " is logged in?");
    }
    
    public void setFirstVisit(boolean is){
        firstVisit = is;
    }
    public PanelCreditCard getCardPanel(){
        return cardPanel;
    }
    public PanelDeliveryInfo getDeliveryPanel(){
        return deliveryPanel;
    }
    public void clearPanels(){
        cardPanel.clearCardInfo();
        deliveryPanel.clearTextFields();
        cardPanel.setLabels();
        deliveryPanel.setLabels();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
