/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imat.panels.contentPanels.buyingPanels;

import imat.models.CustomerModel;
import imat.IMat;
import imat.models.*;
import imat.panels.contentPanels.PanelCreditCard;
import imat.panels.contentPanels.PanelDeliveryInfo;

/**
 *
 * @author Johan Swanberg
 */
public class PanelFillInInfo extends javax.swing.JPanel {
    private PanelInfoForm infoPanel;
    private PanelCreditCard card =  new PanelCreditCard();
    PanelDeliveryInfo delivery = new PanelDeliveryInfo();
    
    /**
     * Creates new form PanelSelectPayment
     */
    public PanelFillInInfo() {
        initComponents();
        card.setSize(500,300);
        delivery.setSize(500, 790);
        jPanel13.add(card);
        jPanel13.add(delivery);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scroller = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        tog4 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        regCheck = new javax.swing.JCheckBox();
        tog2 = new javax.swing.JLabel();
        tog3 = new javax.swing.JTextField();
        tog1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        scroller.setBorder(null);
        scroller.setOpaque(false);

        jPanel2.setOpaque(false);
        scroller.setViewportView(jPanel2);

        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 474));

        tog4.setEnabled(false);

        jButton4.setText("Bekräfta betalningsinfo");
        jButton4.setPreferredSize(new java.awt.Dimension(75, 25));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        regCheck.setText("Spara mina uppgifter");
        regCheck.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxRegItemStateChanged(evt);
            }
        });
        regCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxRegActionPerformed(evt);
            }
        });

        tog2.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        tog2.setText("Repetera Lösenord");
        tog2.setEnabled(false);

        tog3.setEnabled(false);

        tog1.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        tog1.setText("Välj Lösenord");
        tog1.setEnabled(false);

        jButton1.setText("Tillbaka");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed1(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(tog3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tog1)
                        .addGap(24, 24, 24))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(tog4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tog2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(regCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(0, 7, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tog3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tog1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tog4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tog2)
                            .addComponent(regCheck)))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel11.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setBorder(null);

        jPanel13.setLayout(new javax.swing.BoxLayout(jPanel13, javax.swing.BoxLayout.Y_AXIS));
        jPanel12.add(jPanel13);

        jScrollPane2.setViewportView(jPanel12);

        jPanel11.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel3.setPreferredSize(new java.awt.Dimension(620, 70));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(imat.IMat.getAccentColor());
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/wizardsteps/2.png"))); // NOI18N
        jLabel1.setOpaque(true);
        jPanel3.add(jLabel1, java.awt.BorderLayout.SOUTH);

        jPanel4.setBackground(imat.IMat.getAccentColor());

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(250, 250, 250));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Bekräfta Kundvagn");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 13, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 13, Short.MAX_VALUE)))
        );

        jPanel3.add(jPanel4, java.awt.BorderLayout.CENTER);

        add(jPanel3, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if (regCheck.isSelected() == true){
            if (tog2.getText().equals(tog4.getText()) && (card.isAllCorrect() && delivery.isAllCorrect())){
                CustomerModel.setEmail(infoPanel.getMail());
                CustomerModel.setPassword(tog2.getText());
                CustomerModel.setAddress(infoPanel.getAddress());
                CustomerModel.setFirstName(infoPanel.getFirstName());
                CustomerModel.setLastName(infoPanel.getLastName());
                CustomerModel.setPhoneNumber(infoPanel.getPhoneNumber());
                CustomerModel.setPostAddress(infoPanel.getPostAddress());
                CustomerModel.setPostCode(infoPanel.getPostCode());
                CustomerModel.setCardType(infoPanel.getCardType());
                CustomerModel.setCardNumber(infoPanel.getCardNumber());
                CustomerModel.setCardMonth(infoPanel.getCardMonth());
                CustomerModel.setCardYear(infoPanel.getCardYear());
                CustomerModel.setCardHolderName(infoPanel.getCardHolderName());
                CustomerModel.setCardVerification(infoPanel.getCardVerification());
                 finishOrder();
                 IMat.getWindow().setContent(new ConfirmOrderInfo());
            }else{
                System.out.println("something wasnt filled in right");
            }

        }else{
             if ((card.isAllCorrect() && delivery.isAllCorrect())){
                CustomerModel.setEmail(infoPanel.getMail());
                CustomerModel.setAddress(infoPanel.getAddress());
                CustomerModel.setFirstName(infoPanel.getFirstName());
                CustomerModel.setLastName(infoPanel.getLastName());
                CustomerModel.setPhoneNumber(infoPanel.getPhoneNumber());
                CustomerModel.setPostAddress(infoPanel.getPostAddress());
                CustomerModel.setPostCode(infoPanel.getPostCode());
                CustomerModel.setCardType(infoPanel.getCardType());
                CustomerModel.setCardNumber(infoPanel.getCardNumber());
                CustomerModel.setCardMonth(infoPanel.getCardMonth());
                CustomerModel.setCardYear(infoPanel.getCardYear());
                CustomerModel.setCardHolderName(infoPanel.getCardHolderName());
                CustomerModel.setCardVerification(infoPanel.getCardVerification());
                 finishOrder();
                 IMat.getWindow().setContent(new ConfirmOrderInfo());
                }   
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1ActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed1
        IMat.getWindow().setContent(new PanelConfirm());
    }//GEN-LAST:event_jButton1ActionPerformed1

    private void jCheckBoxRegItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxRegItemStateChanged
        if(tog1.isEnabled() == false){
            tog1.setEnabled(true);
            tog2.setEnabled(true);
            tog3.setEnabled(true);
            tog4.setEnabled(true);
        }else{
            tog1.setEnabled(false);
            tog2.setEnabled(false);
            tog3.setEnabled(false);
            tog4.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBoxRegItemStateChanged

    private void jCheckBoxRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxRegActionPerformed

    }//GEN-LAST:event_jCheckBoxRegActionPerformed

private void finishOrder() {
       if (!(Model.getShoppingcart().getItems().isEmpty()) && CustomerModel.isPaymentFilledIn()) {
           IMat.getWindow().setContent(new ConfirmOrderInfo());
        } else{
            System.out.println("theres nothing in the cart to buy! Something went wrong");
        }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox regCheck;
    private javax.swing.JScrollPane scroller;
    private javax.swing.JLabel tog1;
    private javax.swing.JLabel tog2;
    private javax.swing.JTextField tog3;
    private javax.swing.JTextField tog4;
    // End of variables declaration//GEN-END:variables
}
