/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imat.panels.modulePanels;

import imat.models.CustomerModel;
import imat.IMat;
import imat.panels.contentPanels.AccountMixes.MyProfilePanel;
import imat.panels.contentPanels.AccountMixes.MyProfilePanelHolder;
import imat.panels.contentPanels.AccountMixes.RegisterPanel;
import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author Johan
 */
public class loginDefault extends javax.swing.JPanel {

    private boolean visible = true;
    private ImageIcon joinB = new ImageIcon("src/resources/loginButtons/join.jpg");
    private ImageIcon loginB = new ImageIcon("src/resources/loginButtons/login.jpg");
    private ImageIcon profileB = new ImageIcon("src/resources/loginButtons/profil.jpg");
    private ImageIcon logoutB = new ImageIcon("src/resources/loginButtons/logout.jpg");
    private ImageIcon joinHov = new ImageIcon("src/resources/loginButtons/joinHov.jpg");
    private ImageIcon loginHov = new ImageIcon("src/resources/loginButtons/loginHov.jpg");
    private ImageIcon profileHov = new ImageIcon("src/resources/loginButtons/profilHov.jpg");
    private ImageIcon logoutHov = new ImageIcon("src/resources/loginButtons/logoutHov.jpg");
    private ImageIcon joinPressed = new ImageIcon("src/resources/loginButtons/joinPressed.jpg");
    private ImageIcon loginPressed = new ImageIcon("src/resources/loginButtons/loginPressed.jpg");
    private ImageIcon profilePressed = new ImageIcon("src/resources/loginButtons/profilPressed.jpg");
    private ImageIcon logoutPressed = new ImageIcon("src/resources/loginButtons/logoutPressed.jpg");

    /**
     * Creates new form loginDefault
     */
    public loginDefault() {
        initComponents();
        dynamicTextChange();
        toggleVisibleButtons();
        fixColor();
        
    }


    private void fixColor(){
        formPanel.setBackground(IMat.getHeaderColor());
        buttonPanel.setBackground(IMat.getHeaderColor());
        filler.setBackground(IMat.getHeaderColor());
    
    }
    private void toggleVisibleButtons() {

        if (visible == false) {
            usernameInput.setVisible(true);
            passwordInput.setVisible(true);
            okLoginButton.setVisible(true);
            visible = true;
        } else {
            usernameInput.setVisible(false);
            passwordInput.setVisible(false);
            okLoginButton.setVisible(false);
            visible=false;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPanel = new javax.swing.JPanel();
        joinButton = new javax.swing.JLabel();
        loginButton = new javax.swing.JLabel();
        formPanel = new javax.swing.JPanel();
        usernameInput = new javax.swing.JTextField();
        filler = new javax.swing.JPanel();
        passwordInput = new javax.swing.JPasswordField();
        okLoginButton = new javax.swing.JButton();

        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        buttonPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 20, 0, 20));
        buttonPanel.setOpaque(false);
        buttonPanel.setPreferredSize(new java.awt.Dimension(300, 40));
        buttonPanel.setLayout(new java.awt.GridLayout(1, 2, 20, 10));

        joinButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                joinButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                joinButtonMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                joinButtonMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                joinButtonExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                joinButtonEntered(evt);
            }
        });
        buttonPanel.add(joinButton);

        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loginButtonMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginButtonMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginButtonExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginButtonEntered(evt);
            }
        });
        buttonPanel.add(loginButton);

        add(buttonPanel, java.awt.BorderLayout.NORTH);

        formPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 20, 20, 20));
        formPanel.setOpaque(false);
        formPanel.setPreferredSize(new java.awt.Dimension(300, 80));
        formPanel.setLayout(new java.awt.GridLayout(2, 2, 5, 5));

        usernameInput.setText("Email");
        usernameInput.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        usernameInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameInputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameInputFocusLost(evt);
            }
        });
        formPanel.add(usernameInput);

        filler.setOpaque(false);

        javax.swing.GroupLayout fillerLayout = new javax.swing.GroupLayout(filler);
        filler.setLayout(fillerLayout);
        fillerLayout.setHorizontalGroup(
            fillerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 127, Short.MAX_VALUE)
        );
        fillerLayout.setVerticalGroup(
            fillerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        formPanel.add(filler);

        passwordInput.setText("Password");
        passwordInput.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        passwordInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordInputFocusGained(evt);
            }
        });
        formPanel.add(passwordInput);

        okLoginButton.setText("Ok");
        okLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okLoginButtonActionPerformed(evt);
            }
        });
        formPanel.add(okLoginButton);

        add(formPanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void okLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okLoginButtonActionPerformed

        if(usernameInput.getText().equals(CustomerModel.getEmail()) && passwordInput.getText().equals(CustomerModel.getPassword())){
           usernameInput.setBackground(Color.white);
           passwordInput.setBackground(Color.white);
           toggleVisibleButtons();
           loginButton.setIcon(logoutB);
           joinButton.setIcon(profileB);
           IMat.setLoggedin(true);
           
       }else{
           Color errorColor = new Color(255,180,180);
           usernameInput.setBackground(errorColor);
           passwordInput.setBackground(errorColor);
       }
    }//GEN-LAST:event_okLoginButtonActionPerformed

    private void usernameInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameInputFocusGained
        if(usernameInput.getText().equals("Email")){
            usernameInput.setText("");
        }
    }//GEN-LAST:event_usernameInputFocusGained

    private void usernameInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameInputFocusLost
         if(usernameInput.getText().equals("")){
            usernameInput.setText("Email");
        }
    }//GEN-LAST:event_usernameInputFocusLost

    private void passwordInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordInputFocusGained
        passwordInput.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_passwordInputFocusGained

    private void joinButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_joinButtonMouseClicked
        // TODO add your handling code here:
        if(!IMat.isLoggedin()){
            IMat.getWindow().setContent(new RegisterPanel());
        }else{
            IMat.getWindow().setContent(new MyProfilePanelHolder());
        }
    }//GEN-LAST:event_joinButtonMouseClicked

    private void loginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseClicked
        // TODO add your handling code here:
        if (IMat.isLoggedin()){
            IMat.setLoggedin(false);
            dynamicTextChange();
            IMat.getWindow().revalidate();
            IMat.getWindow().repaint();
        }else{
           toggleVisibleButtons();
        }
    }//GEN-LAST:event_loginButtonMouseClicked

    private void joinButtonEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_joinButtonEntered
        // TODO add your handling code here:
        if(IMat.isLoggedin()){
            joinButton.setIcon(profileHov);
        }else{
            joinButton.setIcon(joinHov);
        }
        this.revalidate();
    }//GEN-LAST:event_joinButtonEntered

    private void loginButtonEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonEntered
        // TODO add your handling code here:
        if(IMat.isLoggedin()){
            loginButton.setIcon(logoutHov);
        }else{
            loginButton.setIcon(loginHov);
        }
        this.revalidate();
    }//GEN-LAST:event_loginButtonEntered

    private void joinButtonExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_joinButtonExited
        // TODO add your handling code here:
        if(IMat.isLoggedin()){
            joinButton.setIcon(profileB);
        }else{
            joinButton.setIcon(joinB);
        }
        this.revalidate();
    }//GEN-LAST:event_joinButtonExited

    private void loginButtonExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonExited
        // TODO add your handling code here:
        if(IMat.isLoggedin()){
            loginButton.setIcon(logoutB);
        }else{
            loginButton.setIcon(loginB);
        }
        this.revalidate();
    }//GEN-LAST:event_loginButtonExited

    private void joinButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_joinButtonMousePressed
        // TODO add your handling code here:
        if(IMat.isLoggedin()){
            joinButton.setIcon(profilePressed);
        }else{
            joinButton.setIcon(joinPressed);
        }
        this.revalidate();
    }//GEN-LAST:event_joinButtonMousePressed

    private void joinButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_joinButtonMouseReleased
        // TODO add your handling code here:
        if(IMat.isLoggedin()){
            joinButton.setIcon(profileB);
        }else{
            joinButton.setIcon(joinB);
        }
        this.revalidate();
    }//GEN-LAST:event_joinButtonMouseReleased

    private void loginButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMousePressed
        // TODO add your handling code here:
        if(IMat.isLoggedin()){
            loginButton.setIcon(logoutPressed);
        }else{
            loginButton.setIcon(loginPressed);
        }
        this.revalidate();
    }//GEN-LAST:event_loginButtonMousePressed

    private void loginButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseReleased
        // TODO add your handling code here:
        if(IMat.isLoggedin()){
            loginButton.setIcon(logoutB);
        }else{
            loginButton.setIcon(loginB);
        }
        this.revalidate();
    }//GEN-LAST:event_loginButtonMouseReleased

    private void dynamicTextChange(){
        if(IMat.isLoggedin()){
            loginButton.setIcon(logoutB);
            joinButton.setIcon(profileB);
        }else{
            loginButton.setIcon(loginB);
            joinButton.setIcon(joinB);
        }
        this.revalidate();
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel filler;
    private javax.swing.JPanel formPanel;
    private javax.swing.JLabel joinButton;
    private javax.swing.JLabel loginButton;
    private javax.swing.JButton okLoginButton;
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JTextField usernameInput;
    // End of variables declaration//GEN-END:variables
}
