/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imat.panels.subItems;

import imat.models.Model;
import imat.models.ModelAux;
import java.awt.Color;
import se.chalmers.ait.dat215.project.ShoppingItem;
import imat.panels.contentPanels.buyingPanels.PanelConfirm;

/**
 *
 * @author Johan Swanberg
 */
public class BoughtItem extends javax.swing.JPanel {
    private static boolean zebra = false;
    private ShoppingItem thisItem;
    /**
     * Creates new form BoughtItem
     */
    public BoughtItem(ShoppingItem item) {
        initComponents();
        thisItem=item;
        fixLabels();
        fixZebra();
    }
    
    private void fixZebra(){
        zebra=!zebra;
        if (zebra) {
            setBackground(new Color(250,250,250));
        }else{
            setBackground(new Color(230,230,230));
        }
    }
    private void fixLabels(){
        imageLabel.setIcon(Model.getImage(thisItem.getProduct(),90,90));
        bigNumberLabel.setText(String.valueOf((int)thisItem.getAmount()) + " "+thisItem.getProduct().getUnitSuffix());
        totalCostLabel.setText((int)thisItem.getTotal() + " kr (" + (int)thisItem.getProduct().getPrice() + " /"+thisItem.getProduct().getUnitSuffix() + ")");
        nameLabel.setText(thisItem.getProduct().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        imageLabel = new javax.swing.JLabel();
        colorPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        totalCostLabel = new javax.swing.JLabel();
        bigNumberLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setBorder(null);
        jSplitPane1.setDividerLocation(90);
        jSplitPane1.setDividerSize(0);
        jSplitPane1.setOpaque(false);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(imageLabel, java.awt.BorderLayout.CENTER);

        jSplitPane1.setLeftComponent(jPanel1);

        colorPanel.setBackground(new java.awt.Color(0, 0, 0));
        colorPanel.setOpaque(false);

        nameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nameLabel.setText("The name of the product bought");

        jLabel3.setText("Total kostnad:");

        totalCostLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totalCostLabel.setText("45 kr (15/förp)");

        bigNumberLabel.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        bigNumberLabel.setForeground(new java.awt.Color(0, 102, 51));
        bigNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bigNumberLabel.setText("3");

        javax.swing.GroupLayout colorPanelLayout = new javax.swing.GroupLayout(colorPanel);
        colorPanel.setLayout(colorPanelLayout);
        colorPanelLayout.setHorizontalGroup(
            colorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(colorPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(colorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel)
                    .addGroup(colorPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(totalCostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(bigNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        colorPanelLayout.setVerticalGroup(
            colorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(colorPanelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(colorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(colorPanelLayout.createSequentialGroup()
                        .addComponent(nameLabel)
                        .addGap(2, 2, 2)
                        .addGroup(colorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(colorPanelLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(totalCostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(bigNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jSplitPane1.setRightComponent(colorPanel);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bigNumberLabel;
    private javax.swing.JPanel colorPanel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel totalCostLabel;
    // End of variables declaration//GEN-END:variables
}
