/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imat.panels.subItems;

import imat.IMat;
import imat.models.ModelAux;
import java.awt.Color;
import se.chalmers.ait.dat215.project.ShoppingItem;

/**
 *
 * @author Johan
 */
public class CartItem extends javax.swing.JPanel {
    private static boolean zebra = true;
    private ShoppingItem item;
    /**
     * Creates new form cartItem
     */
    public CartItem() {
        initComponents();
    }
    
      /**
     * Creates new form cartItem
     * @param item a shoppingitem
     */
    public CartItem(ShoppingItem item) {
        initComponents();
        this.item = item;
        amountInput.setText(String.valueOf((int)item.getAmount() + " " + item.getProduct().getUnitSuffix()));
        nameLabel.setText(item.getProduct().getName());
        priceLabel.setText(String.valueOf((int)item.getTotal()) + " kr");
        Color zebra1 = new Color(250,250,250);
        Color zebra2 = new Color(230,230,230);
        
        if(zebra){
            this.setBackground(zebra1);
            amountInput.setBackground(zebra1);
            zebra=false;
        }else{
            this.setBackground(zebra2);
            amountInput.setBackground(zebra2);
            zebra=true;
        }
    }


    private void pressedX() {
      ModelAux.removeAllOfProductFromCart(item);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        amountInput = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        imageLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        regretLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setMaximumSize(new java.awt.Dimension(30, 100));
        setLayout(null);

        amountInput.setText("2");
        add(amountInput);
        amountInput.setBounds(10, 10, 50, 14);

        nameLabel.setText("Köttfärs");
        add(nameLabel);
        nameLabel.setBounds(60, 10, 90, 14);

        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/removeIcon.png"))); // NOI18N
        imageLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageLabelMouseClicked(evt);
            }
        });
        add(imageLabel);
        imageLabel.setBounds(180, 0, 20, 30);

        priceLabel.setForeground(new java.awt.Color(102, 102, 102));
        priceLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        priceLabel.setText("13kr");
        add(priceLabel);
        priceLabel.setBounds(120, 10, 50, 14);
        add(regretLabel);
        regretLabel.setBounds(110, 10, 0, 0);
    }// </editor-fold>//GEN-END:initComponents

    private void imageLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabelMouseClicked
    pressedX();        // TODO add your handling code here:
    }//GEN-LAST:event_imageLabelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountInput;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel regretLabel;
    // End of variables declaration//GEN-END:variables
}
