/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imat.panels.subItems;

import java.awt.Color;
import java.util.List;
import javax.swing.JPanel;
import se.chalmers.ait.dat215.project.Order;
import se.chalmers.ait.dat215.project.ShoppingItem;

/**
 *
 * @author Johan Swanberg
 */
public class CartHistory extends javax.swing.JPanel {
    private Color zebra1 = new Color(245,245,245);
    private Color zebra2 = new Color(250,250,250);
    private Order order;
    private static boolean zebra = false;
    /**
     * Creates new form CartHistory
     */
    public CartHistory(Order inputOrder ) {
        initComponents();
        this.order = inputOrder;
        initLabels();
        toggleZebra();
        fixZebraColor();
    }
    
    private void fixZebraColor(){
        if(zebra){
            this.setBackground(zebra1);
        }else{
            this.setBackground(zebra2);
        }
    }

    private void toggleZebra(){
        if (zebra){
            zebra = false;
        }else{
            zebra = true;
        }
    }
    private void initLabels(){
        dateLabel.setText(order.getDate().toString());
        orderIDLabel.setText(String.valueOf(order.getOrderNumber()));
        contentLabel.setText(getPartialOrder());
        double price = 0;
        
        //get the total cost of a list of shopping items
        List<ShoppingItem> items = order.getItems();
        for (ShoppingItem item : items){
            price += item.getTotal();
        }
        priceLabel.setText(String.valueOf((int)price));
    }
    private String getPartialOrder() {
        String returner = "";
        List<ShoppingItem> items = order.getItems();
        int cntr = 0;
        for (ShoppingItem item : items){
            returner = returner + item.getProduct().getName() + ", " ;
            cntr++;
            if (cntr > 4){
                break;
            }
        }
        
        return returner;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        orderIDLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        contentLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();

        jLabel1.setText("Datum av köp:");

        dateLabel.setText("jLabel2");

        jLabel2.setText("Order ID:");

        orderIDLabel.setText("   ");

        jLabel3.setText("Delvis innehåll:");

        contentLabel.setText("jLabel4");

        jLabel4.setText("pris:");

        priceLabel.setText("pris");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(orderIDLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(contentLabel)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(priceLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateLabel)
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(orderIDLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(contentLabel)
                    .addComponent(jLabel4)
                    .addComponent(priceLabel))
                .addGap(0, 22, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dateLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contentLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel orderIDLabel;
    private javax.swing.JLabel priceLabel;
    // End of variables declaration//GEN-END:variables
}
