/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imat.panels.subItems;

import imat.Model;
import se.chalmers.ait.dat215.project.Product;
import se.chalmers.ait.dat215.project.ShoppingItem;

/**
 *
 * @author Johan
 */
public class GridItem extends javax.swing.JPanel {

    private Product product;
    
        /**
     * Creates new form DetailsItem
     */
    public GridItem(Product product) {
        initComponents();
        this.product = product;
        imageLabel.setIcon(Model.getImage(product, 200 , 200));
        priceLabel.setText(String.valueOf(product.getPrice()));
        
    }
    
    /**
     * Creates new form DetailsItem
     */
    public GridItem() {
        initComponents();
        priceLabel.setText("griditem without item");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        buyButton = new javax.swing.JButton();
        priceLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        imageLabel.setText("  ");
        add(imageLabel, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.GridLayout(1, 3));
        add(jPanel1, java.awt.BorderLayout.PAGE_END);

        buyButton.setText("köp");
        buyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyButtonActionPerformed(evt);
            }
        });
        add(buyButton, java.awt.BorderLayout.PAGE_START);

        priceLabel.setText("  ");
        add(priceLabel, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void buyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyButtonActionPerformed
        ShoppingItem thisItem = new ShoppingItem(product);
        Model.getShoppingcart().addItem(thisItem);
    }//GEN-LAST:event_buyButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buyButton;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel priceLabel;
    // End of variables declaration//GEN-END:variables
}
