/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imat.panels.subItems;

import java.util.Random;

/**
 *
 * @author Johan Swanberg
 */
public class NoResultsPanel extends javax.swing.JPanel {

    /**
     * Creates new form NoResultsPanel
     */
    public NoResultsPanel() {
        initComponents();
        displayJoke();
    }

    private void displayJoke(){
        jokeLabel.setText(getJoke());
    }
    
    private String getJoke(){
        Random rand  = new Random();
        
        int rnd = rand.nextInt(5);
        
        switch (rnd){
            case(1): return "Varför anställer vi rävar?"; 
            case(2): return "För i tiden lät vi rävar ta hand om leveranserna..."; 
            case(3): return "Wa-pa-pa-pa-pa-pa-pow!"; 
            case(4): return "Nyvarande vetenskap antyder att rävar ej kan skilja på rött och grönt."; 
            case(5): return ":P"; 
        }
        return ":3";
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        noResults = new javax.swing.JLabel();
        jokeLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/noresults.png"))); // NOI18N
        add(jLabel1, java.awt.BorderLayout.CENTER);

        noResults.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        noResults.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noResults.setText("Inga resultat hittades");
        add(noResults, java.awt.BorderLayout.NORTH);

        jokeLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jokeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jokeLabel.setText("  ");
        add(jokeLabel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jokeLabel;
    private javax.swing.JLabel noResults;
    // End of variables declaration//GEN-END:variables
}
