/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imat.panels.loginForms;

import imat.IMat;

/**
 *
 * @author Johan
 */
public class loginDefault extends javax.swing.JPanel {

    private boolean visible  = false;
    /**
     * Creates new form loginDefault
     */
    public loginDefault() {
        initComponents();
        usernameInput.setVisible(false);
        passwordInput.setVisible(false);
        okLoginButton.setVisible(false);
    }
    
    private void toggleVisibleButtons(){
        
        if (visible = false){
          usernameInput.setVisible(true);
         passwordInput.setVisible(true);
           okLoginButton.setVisible(true);  
        } else{
             usernameInput.setVisible(false);
         passwordInput.setVisible(false);
           okLoginButton.setVisible(false);  
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPanel = new javax.swing.JPanel();
        joinButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();
        formPanel = new javax.swing.JPanel();
        usernameInput = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        passwordInput = new javax.swing.JTextField();
        okLoginButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        buttonPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 20, 0, 20));
        buttonPanel.setPreferredSize(new java.awt.Dimension(300, 40));
        buttonPanel.setLayout(new java.awt.GridLayout(1, 2, 20, 10));

        joinButton.setText("Gå med");
        buttonPanel.add(joinButton);

        loginButton.setText("Logga in");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(loginButton);

        add(buttonPanel, java.awt.BorderLayout.NORTH);

        formPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 0, 0, 0));
        formPanel.setPreferredSize(new java.awt.Dimension(300, 80));
        formPanel.setLayout(new java.awt.GridLayout(2, 2, 5, 5));

        usernameInput.setText("Användarnamn");
        formPanel.add(usernameInput);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 147, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        formPanel.add(jPanel1);

        passwordInput.setText("Lösenord");
        formPanel.add(passwordInput);

        okLoginButton.setText("Ok");
        formPanel.add(okLoginButton);

        add(formPanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel formPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton joinButton;
    private javax.swing.JButton loginButton;
    private javax.swing.JButton okLoginButton;
    private javax.swing.JTextField passwordInput;
    private javax.swing.JTextField usernameInput;
    // End of variables declaration//GEN-END:variables
}
