/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imat.panels.contentPanels.homeSubContent;

import imat.IMat;
import imat.panels.contentPanels.PanelAccountInfo;
import imat.panels.contentPanels.PanelEarlierCarts;
import imat.panels.contentPanels.PanelFAQ;
import imat.panels.contentPanels.PanelHome;

/**
 *
 * @author Johan
 */
public class loggedInHome extends javax.swing.JPanel {

    /**
     * Creates new form loggedInHome
     */
    public loggedInHome() {
        initComponents();
        currentOrders.setEnabled(false);
        howTo.setEnabled(false);
        offers.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        currentOrders = new javax.swing.JButton();
        jButtonAccoutInfo = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        howTo = new javax.swing.JButton();
        offers = new javax.swing.JButton();
        jButtonFAQ = new javax.swing.JButton();

        setOpaque(false);

        currentOrders.setText("Pågående Beställning");

        jButtonAccoutInfo.setText("Mitt Konto");
        jButtonAccoutInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAccoutInfoActionPerformed(evt);
            }
        });

        jButton5.setText("Tidigare Beställningar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        howTo.setText("Hur gör man?");
        howTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                howToActionPerformed(evt);
            }
        });

        offers.setText("Erbjudanden");
        offers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offersActionPerformed(evt);
            }
        });

        jButtonFAQ.setText("Vanliga Frågor");
        jButtonFAQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFAQActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(howTo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(currentOrders, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(jButtonFAQ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(offers, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jButtonAccoutInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAccoutInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(currentOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(howTo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFAQ, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(offers, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(170, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAccoutInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAccoutInfoActionPerformed
        // TODO add your handling code here:
        IMat.getWindow().setContent(new PanelAccountInfo());
    }//GEN-LAST:event_jButtonAccoutInfoActionPerformed

    private void jButtonFAQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFAQActionPerformed
        // TODO add your handling code here:
        IMat.getWindow().setContent(new PanelFAQ());
    }//GEN-LAST:event_jButtonFAQActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        IMat.getWindow().setContent(new PanelEarlierCarts());        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void howToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_howToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_howToActionPerformed

    private void offersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_offersActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton currentOrders;
    private javax.swing.JButton howTo;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonAccoutInfo;
    private javax.swing.JButton jButtonFAQ;
    private javax.swing.JButton offers;
    // End of variables declaration//GEN-END:variables
}
