/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imat.panels.contentPanels.AccountMixes;

import imat.models.CustomerModel;
import imat.panels.contentPanels.PanelAccountInfo;
import imat.panels.contentPanels.PanelCreditCard;
import imat.panels.contentPanels.PanelDeliveryInfo;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JPanel;

/**
 *
 * @author Morpheus
 */
public class MyProfilePanelHolder extends javax.swing.JPanel {

    private static Color hoverStripe = new Color(160, 160, 160);
    private static Color blackStripe = new Color(120,120,120);
    private static Color whiteStripe = new Color(80,80,80);
    
    private PanelAccountInfo accountCard = new PanelAccountInfo();
    private PanelCreditCard cardCard = new PanelCreditCard();
    private PanelDeliveryInfo deliveryCard = new PanelDeliveryInfo();
    
    private Boolean profileIsClicked = false; 
    private Boolean deliveryIsClicked = false;
    private Boolean cardIsClicked = false;
    
    /**
     * Creates new form MyProfilePanelHolder
     */
    public MyProfilePanelHolder() {
        initComponents();
        initiate();
        
    }
    
    private void initiate(){
        cardPanel.setBackground(whiteStripe);
        profilePanel.setBackground(blackStripe);
        profileIsClicked = true;
        deliveryPanel.setBackground(whiteStripe);
        setContent(accountCard);
        accountCard.setPreferredSize(new Dimension(401, 229));
        deliveryCard.setPreferredSize(new Dimension(486, 437));
    }

    private void clear(){
        holderPanel.removeAll();
    }
    
    private void performConfirmButton(){
        if (cardIsClicked){
            cardPanelConfirm();
        }else if (deliveryIsClicked){
            deliveryPanelConfirm();
        }else{
            accountPanelConfirm();
        }
        
        
        
    }
    
    private void cardPanelConfirm(){
        if(cardCard.isAllCorrect()){
            cardCard.save();
            feedbackLabel.setForeground(Color.green);
            feedbackLabel.setText("Kort sparat!");
        }else{
           feedbackLabel.setForeground(Color.red);
            feedbackLabel.setText("Kort ej sparat!");
        }
    }
    private void deliveryPanelConfirm(){
        if (deliveryCard.isAllCorrect()){
            deliveryCard.save();
            feedbackLabel.setForeground(Color.green);
            feedbackLabel.setText("Leveransupg sparat!");
        }else{
            feedbackLabel.setForeground(Color.red);
            feedbackLabel.setText("leverans ej sparat!");
        }
    }
    private void accountPanelConfirm(){
        if (accountCard.isBothEmailCorrect()&& accountCard.isBothPasswordCorrect()){
            accountCard.save();
            feedbackLabel.setForeground(Color.green);
            feedbackLabel.setText("Kontoupg sparat!");
        }else{ 
            feedbackLabel.setForeground(Color.red);
            feedbackLabel.setText("konto ej sparat!");
        }
    }

    private void setContent(JPanel panel){
                    clear();
                holderPanel.add(panel);
                revalidate();
                repaint();
        }
        
        
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        headerText = new javax.swing.JLabel();
        choicePanel = new javax.swing.JPanel();
        profilePanel = new javax.swing.JPanel();
        profileImage = new javax.swing.JLabel();
        profilLabel = new javax.swing.JLabel();
        deliveryPanel = new javax.swing.JPanel();
        deliveryImage = new javax.swing.JLabel();
        deliveryLabel = new javax.swing.JLabel();
        cardPanel = new javax.swing.JPanel();
        cardImage = new javax.swing.JLabel();
        cardLabel = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        holderPanel = new javax.swing.JPanel();
        feedbackLabel = new javax.swing.JLabel();

        setOpaque(false);

        headerPanel.setBackground(imat.IMat.getAccentColor());
        headerPanel.setPreferredSize(new java.awt.Dimension(581, 75));
        headerPanel.setLayout(new java.awt.BorderLayout());

        headerText.setBackground(imat.IMat.getAccentColor());
        headerText.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        headerText.setForeground(new java.awt.Color(255, 255, 255));
        headerText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerText.setText("Min Profil");
        headerPanel.add(headerText, java.awt.BorderLayout.CENTER);

        choicePanel.setOpaque(false);
        choicePanel.setPreferredSize(new java.awt.Dimension(50, 535));
        choicePanel.setLayout(new java.awt.GridLayout(1, 0));

        profilePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profilePanelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profilePanelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profilePanelMouseEntered(evt);
            }
        });

        profileImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/userPic.png"))); // NOI18N
        profilePanel.add(profileImage);

        profilLabel.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        profilLabel.setForeground(new java.awt.Color(255, 255, 255));
        profilLabel.setText("Profil");
        profilePanel.add(profilLabel);

        choicePanel.add(profilePanel);

        deliveryPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deliveryPanelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deliveryPanelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deliveryPanelMouseEntered(evt);
            }
        });

        deliveryImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/truckImage.png"))); // NOI18N
        deliveryPanel.add(deliveryImage);

        deliveryLabel.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        deliveryLabel.setForeground(new java.awt.Color(255, 255, 255));
        deliveryLabel.setText("Leverans");
        deliveryPanel.add(deliveryLabel);

        choicePanel.add(deliveryPanel);

        cardPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cardPanelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cardPanelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cardPanelMouseEntered(evt);
            }
        });

        cardImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cardImage.png"))); // NOI18N
        cardPanel.add(cardImage);

        cardLabel.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        cardLabel.setForeground(new java.awt.Color(255, 255, 255));
        cardLabel.setText("Kort");
        cardPanel.add(cardLabel);

        choicePanel.add(cardPanel);

        saveButton.setText("Spara ändringar");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        holderPanel.setOpaque(false);

        feedbackLabel.setBackground(new java.awt.Color(0, 204, 0));
        feedbackLabel.setForeground(new java.awt.Color(0, 204, 0));
        feedbackLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
            .addComponent(choicePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(feedbackLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(holderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(choicePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(holderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(feedbackLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deliveryPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deliveryPanelMouseClicked
        // TODO add your handling code here:
        cardPanel.setBackground(whiteStripe);
        profilePanel.setBackground(whiteStripe);
        deliveryPanel.setBackground(blackStripe);
        
        profileIsClicked = false; 
        deliveryIsClicked = true;
        cardIsClicked = false;
        setContent(deliveryCard);
    }//GEN-LAST:event_deliveryPanelMouseClicked

    private void profilePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilePanelMouseClicked
        // TODO add your handling code here:
        cardPanel.setBackground(whiteStripe);
        profilePanel.setBackground(blackStripe);
        deliveryPanel.setBackground(whiteStripe);
        
        profileIsClicked = true; 
        deliveryIsClicked = false;
        cardIsClicked = false;
        setContent(accountCard);
    }//GEN-LAST:event_profilePanelMouseClicked
        
    
    private void cardPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardPanelMouseClicked
        // TODO add your handling code here:
        //holderPanel = cardCard;
        cardPanel.setBackground(blackStripe);
        profilePanel.setBackground(whiteStripe);
        deliveryPanel.setBackground(whiteStripe);
        
        profileIsClicked = false; 
        deliveryIsClicked = false;
        cardIsClicked = true;
        setContent(cardCard);
    }//GEN-LAST:event_cardPanelMouseClicked

    private void profilePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilePanelMouseEntered
        // TODO add your handling code here:
        profilePanel.setBackground(hoverStripe);
    }//GEN-LAST:event_profilePanelMouseEntered

    private void profilePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilePanelMouseExited
        // TODO add your handling code here:
        if (profileIsClicked){
            profilePanel.setBackground(blackStripe);
        }else{
            profilePanel.setBackground(whiteStripe);
        }
    }//GEN-LAST:event_profilePanelMouseExited

    private void deliveryPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deliveryPanelMouseEntered
        // TODO add your handling code here:
        deliveryPanel.setBackground(hoverStripe);
    }//GEN-LAST:event_deliveryPanelMouseEntered

    private void deliveryPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deliveryPanelMouseExited
        // TODO add your handling code here:
        if (deliveryIsClicked){
            deliveryPanel.setBackground(blackStripe);
        }else{
            deliveryPanel.setBackground(whiteStripe);
        }
    }//GEN-LAST:event_deliveryPanelMouseExited

    private void cardPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardPanelMouseEntered
        // TODO add your handling code here:
        cardPanel.setBackground(hoverStripe);
    }//GEN-LAST:event_cardPanelMouseEntered

    private void cardPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardPanelMouseExited
        // TODO add your handling code here:
        if (cardIsClicked){
            cardPanel.setBackground(blackStripe);
        }else{
            cardPanel.setBackground(whiteStripe);
        }
    }//GEN-LAST:event_cardPanelMouseExited

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        performConfirmButton();
    }//GEN-LAST:event_saveButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cardImage;
    private javax.swing.JLabel cardLabel;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JPanel choicePanel;
    private javax.swing.JLabel deliveryImage;
    private javax.swing.JLabel deliveryLabel;
    private javax.swing.JPanel deliveryPanel;
    private javax.swing.JLabel feedbackLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel headerText;
    private javax.swing.JPanel holderPanel;
    private javax.swing.JLabel profilLabel;
    private javax.swing.JLabel profileImage;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
