/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imat.panels.contentPanels.AccountMixes;

import imat.models.CustomerModel;
import imat.panels.contentPanels.PanelAccountInfo;
import imat.panels.contentPanels.PanelCreditCard;
import imat.panels.contentPanels.PanelDeliveryInfo;
import java.awt.Color;

/**
 *
 * @author Morpheus
 */
public class MyProfilePanelHolder extends javax.swing.JPanel {

    private static Color hoverStripe = new Color(160, 160, 160);
    private static Color blackStripe = new Color(120,120,120);
    private static Color whiteStripe = new Color(80,80,80);
    
    private PanelAccountInfo accountCard = new PanelAccountInfo();
    private PanelCreditCard cardCard = new PanelCreditCard();
    private PanelDeliveryInfo deliveryCard = new PanelDeliveryInfo();
    
    private Boolean profileIsClicked = false; 
    private Boolean deliveryIsClicked = false;
    private Boolean cardIsClicked = false;
    
    /**
     * Creates new form MyProfilePanelHolder
     */
    public MyProfilePanelHolder() {
        initComponents();
        initiate();
    }
    
    private void initiate(){
        cardPanel.setBackground(whiteStripe);
        profilePanel.setBackground(blackStripe);
        profileIsClicked = true;
        deliveryPanel.setBackground(whiteStripe);
        holderPanel.setBackground(Color.GREEN);
        holderPanel.add(accountCard);
        revalidate();
    }

    private void performConfirmButton(){
        cardPanelConfirm();
        deliveryPanelConfirm();
        accountPanelConfirm();
        cardCard.save();
    }
    
    private void cardPanelConfirm(){
        if(cardCard.isAllCorrect()){
            cardCard.save();
        }else{
            System.out.println("didnt save card");
            System.out.println(CustomerModel.getCardType());
        }
    }
    private void deliveryPanelConfirm(){
        if (deliveryCard.isAllCorrect()){
            deliveryCard.save();
        }else{
            System.out.println("didnt save delivery info");
        }
    }
    private void accountPanelConfirm(){
        if (accountCard.isEmailCorrect() && accountCard.isPasswordCorrect()){
            accountCard.save();
        }else{ 
            System.out.println("didnt save acc info");
        }
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        headerText = new javax.swing.JLabel();
        choicePanel = new javax.swing.JPanel();
        profilePanel = new javax.swing.JPanel();
        profileImage = new javax.swing.JLabel();
        profilLabel = new javax.swing.JLabel();
        deliveryPanel = new javax.swing.JPanel();
        deliveryImage = new javax.swing.JLabel();
        deliveryLabel = new javax.swing.JLabel();
        cardPanel = new javax.swing.JPanel();
        cardImage = new javax.swing.JLabel();
        cardLabel = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        holderPanel = new javax.swing.JPanel();

        headerPanel.setBackground(imat.IMat.getAccentColor());
        headerPanel.setPreferredSize(new java.awt.Dimension(581, 75));
        headerPanel.setLayout(new java.awt.BorderLayout());

        headerText.setBackground(imat.IMat.getAccentColor());
        headerText.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        headerText.setForeground(new java.awt.Color(255, 255, 255));
        headerText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerText.setText("Min Profil");
        headerPanel.add(headerText, java.awt.BorderLayout.CENTER);

        choicePanel.setPreferredSize(new java.awt.Dimension(50, 535));
        choicePanel.setLayout(new java.awt.GridLayout());

        profilePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profilePanelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profilePanelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profilePanelMouseEntered(evt);
            }
        });

        profileImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/userPic.png"))); // NOI18N
        profilePanel.add(profileImage);

        profilLabel.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        profilLabel.setForeground(new java.awt.Color(255, 255, 255));
        profilLabel.setText("Profil");
        profilePanel.add(profilLabel);

        choicePanel.add(profilePanel);

        deliveryPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deliveryPanelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deliveryPanelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deliveryPanelMouseEntered(evt);
            }
        });

        deliveryImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/truckImage.png"))); // NOI18N
        deliveryPanel.add(deliveryImage);

        deliveryLabel.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        deliveryLabel.setForeground(new java.awt.Color(255, 255, 255));
        deliveryLabel.setText("Leverans");
        deliveryPanel.add(deliveryLabel);

        choicePanel.add(deliveryPanel);

        cardPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cardPanelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cardPanelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cardPanelMouseEntered(evt);
            }
        });

        cardImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cardImage.png"))); // NOI18N
        cardPanel.add(cardImage);

        cardLabel.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        cardLabel.setForeground(new java.awt.Color(255, 255, 255));
        cardLabel.setText("Kort");
        cardPanel.add(cardLabel);

        choicePanel.add(cardPanel);

        saveButton.setText("Spara ändringar");
        saveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveButtonMouseClicked(evt);
            }
        });

        holderPanel.setSize(new java.awt.Dimension(0, 400));

        javax.swing.GroupLayout holderPanelLayout = new javax.swing.GroupLayout(holderPanel);
        holderPanel.setLayout(holderPanelLayout);
        holderPanelLayout.setHorizontalGroup(
            holderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        holderPanelLayout.setVerticalGroup(
            holderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(saveButton)
                .addContainerGap())
            .addComponent(choicePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(holderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(choicePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 412, Short.MAX_VALUE)
                .addComponent(saveButton)
                .addGap(44, 44, 44))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(138, Short.MAX_VALUE)
                    .addComponent(holderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(78, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deliveryPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deliveryPanelMouseClicked
        // TODO add your handling code here:
        cardPanel.setBackground(whiteStripe);
        profilePanel.setBackground(whiteStripe);
        deliveryPanel.setBackground(blackStripe);
        
        profileIsClicked = false; 
        deliveryIsClicked = true;
        cardIsClicked = false;
    }//GEN-LAST:event_deliveryPanelMouseClicked

    private void profilePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilePanelMouseClicked
        // TODO add your handling code here:
        cardPanel.setBackground(whiteStripe);
        profilePanel.setBackground(blackStripe);
        deliveryPanel.setBackground(whiteStripe);
        
        profileIsClicked = true; 
        deliveryIsClicked = false;
        cardIsClicked = false;
    }//GEN-LAST:event_profilePanelMouseClicked

    private void cardPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardPanelMouseClicked
        // TODO add your handling code here:
        holderPanel = cardCard;
        cardPanel.setBackground(blackStripe);
        profilePanel.setBackground(whiteStripe);
        deliveryPanel.setBackground(whiteStripe);
        
        profileIsClicked = false; 
        deliveryIsClicked = false;
        cardIsClicked = true;
    }//GEN-LAST:event_cardPanelMouseClicked

    private void profilePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilePanelMouseEntered
        // TODO add your handling code here:
        profilePanel.setBackground(hoverStripe);
    }//GEN-LAST:event_profilePanelMouseEntered

    private void profilePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilePanelMouseExited
        // TODO add your handling code here:
        if (profileIsClicked){
            profilePanel.setBackground(blackStripe);
        }else{
            profilePanel.setBackground(whiteStripe);
        }
    }//GEN-LAST:event_profilePanelMouseExited

    private void deliveryPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deliveryPanelMouseEntered
        // TODO add your handling code here:
        deliveryPanel.setBackground(hoverStripe);
    }//GEN-LAST:event_deliveryPanelMouseEntered

    private void deliveryPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deliveryPanelMouseExited
        // TODO add your handling code here:
        if (deliveryIsClicked){
            deliveryPanel.setBackground(blackStripe);
        }else{
            deliveryPanel.setBackground(whiteStripe);
        }
    }//GEN-LAST:event_deliveryPanelMouseExited

    private void cardPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardPanelMouseEntered
        // TODO add your handling code here:
        cardPanel.setBackground(hoverStripe);
    }//GEN-LAST:event_cardPanelMouseEntered

    private void cardPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardPanelMouseExited
        // TODO add your handling code here:
        if (cardIsClicked){
            cardPanel.setBackground(blackStripe);
        }else{
            cardPanel.setBackground(whiteStripe);
        }
    }//GEN-LAST:event_cardPanelMouseExited

    private void saveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveButtonMouseClicked
        // TODO add your handling code here:
        performConfirmButton();
    }//GEN-LAST:event_saveButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cardImage;
    private javax.swing.JLabel cardLabel;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JPanel choicePanel;
    private javax.swing.JLabel deliveryImage;
    private javax.swing.JLabel deliveryLabel;
    private javax.swing.JPanel deliveryPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel headerText;
    private javax.swing.JPanel holderPanel;
    private javax.swing.JLabel profilLabel;
    private javax.swing.JLabel profileImage;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
