/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imat.panels.contentPanels.AccountMixes;

import imat.IMat;
import imat.panels.contentPanels.PanelAccountInfo;
import imat.panels.contentPanels.PanelHome;
import javax.swing.KeyStroke;

/**
 *
 * @author Johan Swanberg
 */
public class RegisterPanel extends javax.swing.JPanel {

    private PanelAccountInfo accPanel = new PanelAccountInfo();
    /**
     * Creates new form RegisterPanel
     */
    public RegisterPanel() {
        initComponents();
        holderPanel.add(accPanel);
    }
    
    private void registerPressed(){
           if (accPanel.isBothEmailCorrect()&& accPanel.isBothPasswordCorrect()){
            accPanel.save();
            IMat.setLoggedin(true);
            IMat.getWindow().setContent(new PanelHome());
    }else{
               errorText.setText("Korrigera felmarkerade fält");
           }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        asd = new javax.swing.JPanel();
        holderPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        errorText = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        asd.setOpaque(false);

        holderPanel.setMinimumSize(new java.awt.Dimension(500, 300));
        holderPanel.setOpaque(false);
        holderPanel.setPreferredSize(new java.awt.Dimension(500, 300));
        holderPanel.setLayout(new java.awt.BorderLayout());
        asd.add(holderPanel);

        jButton1.setBackground(imat.IMat.getAccentColor());
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(250, 250, 250));
        jButton1.setText("Genomför registrering");
        jButton1.setPreferredSize(new java.awt.Dimension(160, 40));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        asd.add(jButton1);
        asd.add(errorText);

        add(asd, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(imat.IMat.getAccentColor());
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel1.setForeground(new java.awt.Color(250, 250, 250));
        jPanel1.setPreferredSize(new java.awt.Dimension(146, 75));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(250, 250, 250));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registrering");
        jLabel1.setPreferredSize(new java.awt.Dimension(126, 75));
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       registerPressed(); // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel asd;
    private javax.swing.JLabel errorText;
    private javax.swing.JPanel holderPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
