/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imat.contentPanels;

import imat.IMat;
import imat.Model;
import imat.panels.subItems.CartHistory;
import java.awt.GridLayout;
import java.util.List;
import javax.swing.JLabel;
import se.chalmers.ait.dat215.project.Order;

/**
 *
 * @author Johan Swanberg
 */
public class PanelEarlierCarts extends javax.swing.JPanel {

    /**
     * Creates new form PanelEarlierCarts
     */
    public PanelEarlierCarts() {
        initComponents();
        List<Order> orders = Model.getOrders();
        cartList.setLayout(new GridLayout(orders.size(),1));
        for (Order order : orders) {
            System.out.println("asd");
            cartList.add(new CartHistory(order));

        }
        if (orders.size() == 0 ){
            cartList.add(new JLabel("Du har inga tidigare beställningar."));
            
        }
        this.revalidate();
        earlierOrderLabel.setBackground(IMat.getAccentColor());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        cartList = new javax.swing.JPanel();
        earlierOrderLabel = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBorder(null);

        cartList.setOpaque(false);

        javax.swing.GroupLayout cartListLayout = new javax.swing.GroupLayout(cartList);
        cartList.setLayout(cartListLayout);
        cartListLayout.setHorizontalGroup(
            cartListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
        );
        cartListLayout.setVerticalGroup(
            cartListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(cartList);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        earlierOrderLabel.setBackground(new java.awt.Color(102, 255, 102));
        earlierOrderLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        earlierOrderLabel.setForeground(new java.awt.Color(255, 255, 255));
        earlierOrderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        earlierOrderLabel.setText("Tidigare beställningar:");
        earlierOrderLabel.setOpaque(true);
        add(earlierOrderLabel, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cartList;
    private javax.swing.JLabel earlierOrderLabel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
