/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imat.contentPanels;

import imat.CustomerModel;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Viktor
 */
public class PanelCreditCard extends javax.swing.JPanel {

    /**
     * Creates new form PanelCreditCard
     */
    public PanelCreditCard() {
        initComponents();
        cardNumberTextField.setText(CustomerModel.getCardNumber());
        cardHolderTextField.setText(CustomerModel.getCardHolderName());
        securityNumberTextField.setText("" + CustomerModel.getCardVerification());
        monthComboBox.setSelectedIndex(CustomerModel.getCardMonth());
        yearComboBox.setSelectedIndex(CustomerModel.getCardYear());
        cardTypeButtonGroup.add(americanRadioButton);
        cardTypeButtonGroup.add(visaMasterRadioButton);
        setSelectedCardType(CustomerModel.getCardType());
        setDigitsLabel(CustomerModel.getCardType());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardTypeButtonGroup = new javax.swing.ButtonGroup();
        visaMasterRadioButton = new javax.swing.JRadioButton();
        americanRadioButton = new javax.swing.JRadioButton();
        cardTypeLabel = new javax.swing.JLabel();
        carNumberLabel = new javax.swing.JLabel();
        cardHolderLabel = new javax.swing.JLabel();
        cardExpireLabel = new javax.swing.JLabel();
        cardSecurityLabel = new javax.swing.JLabel();
        digitsInCardNumberLabel = new javax.swing.JLabel();
        cardHolderTextField = new javax.swing.JTextField();
        monthComboBox = new javax.swing.JComboBox();
        yearComboBox = new javax.swing.JComboBox();
        securityReminderLabel = new javax.swing.JLabel();
        cardHolderReminderLabel = new javax.swing.JLabel();
        cardNumberTextField = new javax.swing.JFormattedTextField();
        securityNumberTextField = new javax.swing.JFormattedTextField();

        setOpaque(false);

        visaMasterRadioButton.setText("VISA/MasterCard");
        visaMasterRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visaMasterRadioButtonActionPerformed(evt);
            }
        });

        americanRadioButton.setText("American Express");
        americanRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                americanRadioButtonActionPerformed(evt);
            }
        });

        cardTypeLabel.setText("Korttyp:");

        carNumberLabel.setText("Kortnummer:");

        cardHolderLabel.setText("Kortinnehavare:");

        cardExpireLabel.setText("Giltighetstid:");

        cardSecurityLabel.setText("CVV2-nummer:");

        digitsInCardNumberLabel.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        digitsInCardNumberLabel.setText("16 siffror");

        cardHolderTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cardHolderTextFieldFocusGained(evt);
            }
        });

        monthComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Januari", "Februari", "Mars", "April", "Maj", "Juni", "Juli", "Augusti", "September", "Oktober", "November", "December" }));

        yearComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022" }));

        securityReminderLabel.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        securityReminderLabel.setText("Sista 3 siffrorna på kortets baksida");

        cardHolderReminderLabel.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        cardHolderReminderLabel.setText("Namn på kortet");

        cardNumberTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        cardNumberTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cardNumberTextFieldFocusGained(evt);
            }
        });

        securityNumberTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        securityNumberTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                securityNumberTextFieldFocusGained(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cardTypeLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(carNumberLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cardHolderLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cardExpireLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cardSecurityLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(visaMasterRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(americanRadioButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(monthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                        .addComponent(yearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cardHolderTextField)
                                    .addComponent(cardNumberTextField))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(digitsInCardNumberLabel)
                                    .addComponent(cardHolderReminderLabel)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(securityNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(securityReminderLabel)))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(visaMasterRadioButton)
                    .addComponent(americanRadioButton)
                    .addComponent(cardTypeLabel))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carNumberLabel)
                    .addComponent(digitsInCardNumberLabel)
                    .addComponent(cardNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardHolderLabel)
                    .addComponent(cardHolderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardHolderReminderLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardExpireLabel)
                    .addComponent(monthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardSecurityLabel)
                    .addComponent(securityReminderLabel)
                    .addComponent(securityNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void visaMasterRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visaMasterRadioButtonActionPerformed
        CustomerModel.setCardType("VISA/MasterCard");
        setDigitsLabel("VISA/MasterCard");
    }//GEN-LAST:event_visaMasterRadioButtonActionPerformed

    private void americanRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_americanRadioButtonActionPerformed
        CustomerModel.setCardType("American Express");
        setDigitsLabel("American Express");
    }//GEN-LAST:event_americanRadioButtonActionPerformed

    private void cardNumberTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cardNumberTextFieldFocusGained
        cancelAllErrors(cardNumberTextField,digitsInCardNumberLabel);       
    }//GEN-LAST:event_cardNumberTextFieldFocusGained

    private void cardHolderTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cardHolderTextFieldFocusGained
        cancelAllErrors(cardHolderTextField,cardHolderReminderLabel);
    }//GEN-LAST:event_cardHolderTextFieldFocusGained

    private void securityNumberTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_securityNumberTextFieldFocusGained
        cancelAllErrors(securityNumberTextField,securityReminderLabel);
    }//GEN-LAST:event_securityNumberTextFieldFocusGained
    /**
     * saves the checked card type
     */
    private void setSelectedCardType(String str) {
        if (str.equals("American Express")) {
            americanRadioButton.setSelected(true);
        } else {
            visaMasterRadioButton.setSelected(true);
        }
    }

    /**
     * sets reminder label for card numbers
     */
    private void setDigitsLabel(String str) {
        if (str.equals("American Express")) {
            digitsInCardNumberLabel.setText("15 siffror");
        } else {
            digitsInCardNumberLabel.setText("16 siffror");
        }
    }

    /**
     * saves all field data
     */
    public void save() {
        CustomerModel.setCardNumber(cardNumberTextField.getText());
        CustomerModel.setCardVerification(Integer.parseInt(securityNumberTextField.getText()));
        CustomerModel.setCardHolderName(cardHolderTextField.getText());
        CustomerModel.setCardMonth(monthComboBox.getSelectedIndex());
        CustomerModel.setCardYear(yearComboBox.getSelectedIndex());
    }

    /**
     * @return true if card number is filled correctly
     */
    public boolean isCardNumberCorrect() {
        return (CustomerModel.cardNumberTest(cardNumberTextField.getText()));
    }

    /**
     * @return true if security number is filled correctly
     */
    public boolean isSecNumberCorrect() {
        return (CustomerModel.cardVerificationTest(securityNumberTextField.getText()));
    }

    /**
     * @return true if card holder name is filled correctly
     */
    public boolean isCardHolderNameCorrect() {
        return (CustomerModel.cardHolderNameTest(cardHolderTextField.getText()));
    }

    /**
     * make a textinputbox show red
     * @param input what textinputbox to make red.
     */
    public void showError(JTextField input) {
        input.setBackground(new Color(240, 200, 200));        
    }
    public void showLabelError(JLabel input){
        input.setForeground(Color.red);
    }
    /** 
     *make a textinputbox show white
     * @param input what textinputbox to revert to white.
     */
    private void cancelError(JTextField input) {
        input.setBackground(Color.WHITE);
    }
    private void cancelLabelError(JLabel input){
        input.setForeground(Color.BLACK);
    }
    private void cancelAllErrors(JTextField textField, JLabel label){
        cancelError(textField);
        cancelLabelError(label);
    }

    public void showNameError() {
        showError(cardHolderTextField);
        showLabelError(cardHolderReminderLabel);
    }

    public void showSecNumberError() {
        showError(securityNumberTextField);
        showLabelError(securityReminderLabel);
    }

    public void showCardNumberError() {
        showError(cardNumberTextField);
        showLabelError(digitsInCardNumberLabel);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton americanRadioButton;
    private javax.swing.JLabel carNumberLabel;
    private javax.swing.JLabel cardExpireLabel;
    private javax.swing.JLabel cardHolderLabel;
    private javax.swing.JLabel cardHolderReminderLabel;
    private javax.swing.JTextField cardHolderTextField;
    private javax.swing.JFormattedTextField cardNumberTextField;
    private javax.swing.JLabel cardSecurityLabel;
    private javax.swing.ButtonGroup cardTypeButtonGroup;
    private javax.swing.JLabel cardTypeLabel;
    private javax.swing.JLabel digitsInCardNumberLabel;
    private javax.swing.JComboBox monthComboBox;
    private javax.swing.JFormattedTextField securityNumberTextField;
    private javax.swing.JLabel securityReminderLabel;
    private javax.swing.JRadioButton visaMasterRadioButton;
    private javax.swing.JComboBox yearComboBox;
    // End of variables declaration//GEN-END:variables
}
