/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imat.contentPanels;

import imat.panels.PanelNavigation;
import imat.panels.subItems.DetailItem;
import imat.panels.subItems.GridItem;
import imat.panels.subItems.ListItem;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.util.List;
import javax.swing.JLabel;
import se.chalmers.ait.dat215.project.Product;
import se.chalmers.ait.dat215.project.ProductCategory;

/**
 *
 * @author Johan
 */
public class PanelSearchResult extends javax.swing.JPanel {

    private List<Product> products;

    /**
     * Creates new form PanelSearchResult
     */
    public PanelSearchResult(List<Product> list) {
        products = list;
        initComponents();

    }

    /**
     * create the list of detailitems and put them in the stuff
     *
     * @param products what products to show
     */
    private void showDetailsResults(List<Product> products) {

        detailsView.setLayout(new GridLayout(products.size(), 1));
        int height = products.size() * 85;
        Dimension dim = new Dimension(500, height);

        detailsView.setPreferredSize(dim);

        for (Product product : products) {
            detailsView.add(new DetailItem(product));
        }
        this.revalidate();
    }

    /**
     * create the list of detailitems and put them in the stuff
     *
     * @param products what products to show
     */
    private void showDetailsResultsGrouped(List<Product> products) {

        int rows = products.size();
        int height = products.size() * 85;
        ProductCategory category = null;
        for (Product product : products) {

            if (category == product.getCategory()) {

                System.out.println(category + "is old");
            } else {
                category = product.getCategory();
                detailsView.add(new JLabel(category.toString()));
                rows++;
                height += 20;
            }

            detailsView.add(new DetailItem(product));
        }

        detailsView.setLayout(new GridLayout(rows, 1));
      
        Dimension dim = new Dimension(500, height);

        detailsView.setPreferredSize(dim);
        this.revalidate();
    }

    /**
     * create a list of gridresults and put them in results.
     *
     * @param products
     */
    private void showGridResults(List<Product> products) {
        gridView.setLayout(new FlowLayout(FlowLayout.CENTER));

        gridView.setPreferredSize(new Dimension(500, 7000));
        for (Product product : products) {
            gridView.add(new GridItem(product));
        }

        this.revalidate();

    }

    /**
     * create a list of listresultitems and put them in resultview
     *
     * @param products what products to show
     */
    private void showListResults(List<Product> products) {
        listView.setLayout(new GridLayout(products.size(), 1));
        int height = products.size() * 50;
        Dimension dim = new Dimension(500, height);

        listView.setPreferredSize(dim);

        for (Product product : products) {
            listView.add(new ListItem(product));
        }
        this.revalidate();
    }

    /**
     * Creates new form PanelSearchResult
     */
    public PanelSearchResult() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        groupCheckbox = new javax.swing.JCheckBox();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        tabPanel = new javax.swing.JTabbedPane();
        detailsViewWrapper = new javax.swing.JScrollPane();
        detailsView = new javax.swing.JPanel();
        listViewWrapper = new javax.swing.JScrollPane();
        listView = new javax.swing.JPanel();
        gridViewWrapper = new javax.swing.JScrollPane();
        gridView = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(677, 40));

        groupCheckbox.setText("Gruppera kategorier");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Populäritet", "Alfabetisk", "Pris" }));

        jLabel1.setText("Sortera på");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(groupCheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 412, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(groupCheckbox)))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        tabPanel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabPanelStateChanged(evt);
            }
        });

        javax.swing.GroupLayout detailsViewLayout = new javax.swing.GroupLayout(detailsView);
        detailsView.setLayout(detailsViewLayout);
        detailsViewLayout.setHorizontalGroup(
            detailsViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        detailsViewLayout.setVerticalGroup(
            detailsViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        detailsViewWrapper.setViewportView(detailsView);

        tabPanel.addTab("Detaljvy", detailsViewWrapper);

        javax.swing.GroupLayout listViewLayout = new javax.swing.GroupLayout(listView);
        listView.setLayout(listViewLayout);
        listViewLayout.setHorizontalGroup(
            listViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        listViewLayout.setVerticalGroup(
            listViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        listViewWrapper.setViewportView(listView);

        tabPanel.addTab("Listvy", listViewWrapper);

        javax.swing.GroupLayout gridViewLayout = new javax.swing.GroupLayout(gridView);
        gridView.setLayout(gridViewLayout);
        gridViewLayout.setHorizontalGroup(
            gridViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        gridViewLayout.setVerticalGroup(
            gridViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        gridViewWrapper.setViewportView(gridView);

        tabPanel.addTab("Gridvy", gridViewWrapper);

        add(tabPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tabPanelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabPanelStateChanged
        loadResult(tabPanel.getSelectedIndex());
    }//GEN-LAST:event_tabPanelStateChanged

    private void loadResult(int i) {
        switch (i) {
            case (0):
                showDetailsResultsGrouped(products);
                break;
            case (1):
                showListResults(products);
                break;
            case (2):
                showGridResults(products);
                break;

        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel detailsView;
    private javax.swing.JScrollPane detailsViewWrapper;
    private javax.swing.JPanel gridView;
    private javax.swing.JScrollPane gridViewWrapper;
    private javax.swing.JCheckBox groupCheckbox;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel listView;
    private javax.swing.JScrollPane listViewWrapper;
    private javax.swing.JTabbedPane tabPanel;
    // End of variables declaration//GEN-END:variables
}
