/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imat.contentPanels;

import imat.CustomerModel;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Viktor
 */
public class PanelAccountInfo extends javax.swing.JPanel {

    /**
     * Creates new form PanelAccount
     */
    public PanelAccountInfo() {
        initComponents();
        emailTextField.setHint("Email");
        //emailTextField.setText(CustomerModel.getEmail());
        newPasswordTextField.setText(CustomerModel.getPassword());//Temporär
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emailLabel = new javax.swing.JLabel();
        repeatEmailLabel = new javax.swing.JLabel();
        repeatEmailTextField = new javax.swing.JTextField();
        newPasswordLabel = new javax.swing.JLabel();
        repeatPasswordLabel = new javax.swing.JLabel();
        newPasswordTextField = new javax.swing.JPasswordField();
        repeatPasswordTextField = new javax.swing.JPasswordField();
        mailErrorlabel = new javax.swing.JLabel();
        passwordErrorLabel = new javax.swing.JLabel();
        emailTextField = new imat.TextFieldWithHint();

        emailLabel.setText("E-post:");

        repeatEmailLabel.setText("Repetera e-post:");

        repeatEmailTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                repeatEmailTextFieldFocusGained(evt);
            }
        });

        newPasswordLabel.setText("Nytt lösenord:");

        repeatPasswordLabel.setText("Repetera lösenord:");

        mailErrorlabel.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        mailErrorlabel.setForeground(java.awt.Color.red);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(repeatEmailTextField)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(newPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(repeatPasswordTextField))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(repeatEmailLabel)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(newPasswordLabel)
                                    .addGap(87, 87, 87)
                                    .addComponent(repeatPasswordLabel))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(emailLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(mailErrorlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(6, 6, 6))
                        .addComponent(passwordErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(mailErrorlabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(repeatEmailLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(repeatEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 5, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPasswordLabel)
                    .addComponent(repeatPasswordLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(repeatPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void repeatEmailTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_repeatEmailTextFieldFocusGained
        cancelError(repeatEmailTextField);
    }//GEN-LAST:event_repeatEmailTextFieldFocusGained

    /**
     * Saves both fields
     */
    public void save() {
        CustomerModel.setPassword(newPasswordTextField.getText());
        CustomerModel.setEmail(emailTextField.getText());
    }

    /**
     * check if email is filled in correctly
     *
     * @return true if both emails are correct
     */
    public boolean isEmailCorrect() {
        return (CustomerModel.emailTest(emailTextField.getText())
                && emailTextField.getText().equals(repeatEmailTextField.getText()));
    }

    /**
     * check if both passwordfields are correct
     *
     * @return true if both are correct and matching
     */
    public boolean isPasswordCorrect() {
        return (newPasswordTextField.getText().equals(repeatPasswordTextField.getText())
                && CustomerModel.passwordTest(newPasswordTextField.getText()));
    }

    /**
     * make a textinputbox show red
     * @param input what textinputbox to make red.
     */
    public void showError(JTextField input) {
        input.setBackground(new Color(240, 200, 200));
    }
        public void showLabelError(JLabel input, String str) {
        input.setText(str);
    }
     /**
     * make a textinputbox show white
     * @param input what textinputbox to make red.
     */
    private void cancelError(JTextField input){
        input.setBackground(Color.WHITE);
    }
      private void cancelLabelError(JLabel input) {
        input.setText("");
    }
    private void cancelAllErrors(JTextField textField, JLabel label) {
        cancelError(textField);
        cancelLabelError(label);
    }

    /**
     * make all textinputs show error
     */
    public void showAllErrors() {
        //showError(emailTextField);
        showError(repeatEmailTextField);
        showError(newPasswordTextField);
        showError(repeatPasswordTextField);
        showLabelError(passwordErrorLabel,"Felaktigt lösenord");
        showLabelError(mailErrorlabel,"Felaktigt e-post adress");
    }

    public void showPassError() {
        showError(newPasswordTextField);
        showError(repeatPasswordTextField);
      showLabelError(passwordErrorLabel,"Felaktigt lösenord");
    }

    public void showEmailError() {
        //showError(emailTextField);
        showError(repeatEmailTextField);
        showLabelError(mailErrorlabel,"Felaktigt e-post adress");
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel emailLabel;
    private imat.TextFieldWithHint emailTextField;
    private javax.swing.JLabel mailErrorlabel;
    private javax.swing.JLabel newPasswordLabel;
    private javax.swing.JPasswordField newPasswordTextField;
    private javax.swing.JLabel passwordErrorLabel;
    private javax.swing.JLabel repeatEmailLabel;
    private javax.swing.JTextField repeatEmailTextField;
    private javax.swing.JLabel repeatPasswordLabel;
    private javax.swing.JPasswordField repeatPasswordTextField;
    // End of variables declaration//GEN-END:variables
}
