/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imat.contentPanels;

import imat.CustomerModel;



/**
 *
 * @author Viktor
 */
public class PanelAccountInfo extends javax.swing.JPanel {

    /**
     * Creates new form PanelAccount
     */
    public PanelAccountInfo() {
        initComponents();
        firstNameTextField.setText(CustomerModel.getFirstName());
        lastNameTextField.setText(CustomerModel.getLastName());
        addressTextField.setText(CustomerModel.getAddress());
        postCodeTextField.setText(CustomerModel.getPostCode());
        postAddressTextField.setText(CustomerModel.getPostAddress());
        phoneNumberTextField.setText(CustomerModel.getPhoneNumber());
        emailTextField.setText(CustomerModel.getEmail());
        newPasswordTextField.setText(CustomerModel.getPassword());//Temporär
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        careOfLabel = new javax.swing.JLabel();
        addressTextField = new javax.swing.JTextField();
        careOfTextField = new javax.swing.JTextField();
        postCodeLabel = new javax.swing.JLabel();
        postAddressLabel = new javax.swing.JLabel();
        postAddressTextField = new javax.swing.JTextField();
        phoneNumberLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        repeatEmailLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        repeatEmailTextField = new javax.swing.JTextField();
        newPasswordLabel = new javax.swing.JLabel();
        repeatPasswordLabel = new javax.swing.JLabel();
        newPasswordTextField = new javax.swing.JTextField();
        repeatPasswordTextField = new javax.swing.JTextField();
        saveAccountButton = new javax.swing.JButton();
        postCodeTextField = new javax.swing.JFormattedTextField();
        phoneNumberTextField = new javax.swing.JFormattedTextField();

        firstNameLabel.setText("Förnamn:");

        lastNameLabel.setText("Efternamn:");

        firstNameTextField.setAutoscrolls(false);
        firstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextFieldActionPerformed(evt);
            }
        });

        addressLabel.setText("Gaturadress:");

        careOfLabel.setText("C/O:");

        postCodeLabel.setText("Postnummer:");

        postAddressLabel.setText("Postort:");

        phoneNumberLabel.setText("Telefon:");

        emailLabel.setText("E-post:");

        repeatEmailLabel.setText("Repetera e-post:");

        repeatEmailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repeatEmailTextFieldActionPerformed(evt);
            }
        });

        newPasswordLabel.setText("Nytt lösenord:");

        repeatPasswordLabel.setText("Repetera lösenord:");

        repeatPasswordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repeatPasswordTextFieldActionPerformed(evt);
            }
        });

        saveAccountButton.setText("Spara uppgifter");
        saveAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAccountButtonActionPerformed(evt);
            }
        });

        postCodeTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(repeatEmailTextField)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(firstNameLabel)
                                .addComponent(firstNameTextField)
                                .addComponent(postCodeLabel)
                                .addComponent(addressLabel)
                                .addComponent(addressTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                .addComponent(emailLabel)
                                .addComponent(phoneNumberLabel)
                                .addComponent(postCodeTextField))
                            .addGap(74, 74, 74)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(postAddressLabel)
                                .addComponent(lastNameLabel)
                                .addComponent(lastNameTextField)
                                .addComponent(careOfLabel)
                                .addComponent(careOfTextField)
                                .addComponent(postAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(emailTextField)
                        .addComponent(repeatEmailLabel)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(newPasswordLabel)
                            .addGap(87, 87, 87)
                            .addComponent(repeatPasswordLabel))
                        .addComponent(saveAccountButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(repeatPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(phoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(lastNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLabel)
                    .addComponent(careOfLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(careOfTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(postCodeLabel)
                    .addComponent(postAddressLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(postAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(postCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(phoneNumberLabel)
                .addGap(13, 13, 13)
                .addComponent(phoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailLabel)
                .addGap(9, 9, 9)
                .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(repeatEmailLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(repeatEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPasswordLabel)
                    .addComponent(repeatPasswordLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(repeatPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(saveAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextFieldActionPerformed

    private void repeatEmailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repeatEmailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_repeatEmailTextFieldActionPerformed

    private void saveAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAccountButtonActionPerformed
        CustomerModel.setFirstName(firstNameTextField.getText());
        CustomerModel.setLastName(lastNameTextField.getText());
        CustomerModel.setAddress(addressTextField.getText());
        CustomerModel.setPostCode(postCodeTextField.getText());
        CustomerModel.setPostAddress(postAddressTextField.getText());
        CustomerModel.setPhoneNumber(phoneNumberTextField.getText());
        CustomerModel.setEmail(emailTextField.getText());
        setPassword();
    }//GEN-LAST:event_saveAccountButtonActionPerformed

    private void repeatPasswordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repeatPasswordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_repeatPasswordTextFieldActionPerformed

    private void setPassword(){
        if(newPasswordTextField.getText().equals(repeatPasswordTextField.getText())){
            CustomerModel.setPassword(newPasswordTextField.getText());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JLabel careOfLabel;
    private javax.swing.JTextField careOfTextField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JLabel newPasswordLabel;
    private javax.swing.JTextField newPasswordTextField;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JFormattedTextField phoneNumberTextField;
    private javax.swing.JLabel postAddressLabel;
    private javax.swing.JTextField postAddressTextField;
    private javax.swing.JLabel postCodeLabel;
    private javax.swing.JFormattedTextField postCodeTextField;
    private javax.swing.JLabel repeatEmailLabel;
    private javax.swing.JTextField repeatEmailTextField;
    private javax.swing.JLabel repeatPasswordLabel;
    private javax.swing.JTextField repeatPasswordTextField;
    private javax.swing.JButton saveAccountButton;
    // End of variables declaration//GEN-END:variables
}
